In [1]:
import torch
print(torch.__version__)

2.1.0+cu118


# Creating Tensor

In [2]:
scala=torch.tensor(7)
scala

tensor(7)

In [3]:
scala.ndim

0

In [4]:
scala.item()

7

# vector


In [5]:
vec=torch.tensor([4,4])
vec

tensor([4, 4])

In [6]:
vec.ndim

1

In [7]:
vec.shape

torch.Size([2])

In [8]:
matrix=torch.tensor([[4,6],
                     [20,10]])
matrix

tensor([[ 4,  6],
        [20, 10]])

In [9]:
matrix.ndim
print("Matrix shape :",matrix.shape)

Matrix shape : torch.Size([2, 2])


In [10]:
three_matrix=torch.tensor([[[8,2,3],
                            [4,5,6],
                            [7,8,9]]])
print("Dimension :",three_matrix.ndim)
print("shape :",three_matrix.shape)

Dimension : 3
shape : torch.Size([1, 3, 3])


# Random Tensor

In [11]:
randm=torch.rand(3,4) # 3 rows 4 cols
randm

tensor([[0.9532, 0.8115, 0.9481, 0.8183],
        [0.9318, 0.8767, 0.2978, 0.9471],
        [0.0038, 0.9850, 0.2370, 0.8957]])

In [12]:
randm=torch.rand(2,3,4) # 3 rows 4 cols
randm

tensor([[[0.4743, 0.0965, 0.5561, 0.3574],
         [0.7160, 0.1509, 0.5248, 0.0952],
         [0.1026, 0.7838, 0.7357, 0.9383]],

        [[0.9386, 0.8883, 0.7070, 0.4968],
         [0.9342, 0.2043, 0.1228, 0.4588],
         [0.8331, 0.8553, 0.9865, 0.9896]]])

In [13]:
randm.ndim

3

In [14]:
image_tensor=torch.rand(size=(224,224,3)) #height,#width,# color_channel

In [15]:
image_tensor.shape

torch.Size([224, 224, 3])

In [16]:
image_tensor.ndim

3

In [17]:
# Zeros and Ones
zeros=torch.zeros(size=(5,5))
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [18]:
ones=torch.ones(size=(4,5))
print(ones)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [19]:
ones.dtype

torch.float32

# Creating range

In [20]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x=torch.arange(start=1,end=22,step=2)
print(x)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])


In [22]:
y=torch.zeros_like(input=x)
print(y)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [23]:
m=torch.tensor([1.0,3.8,5.7],dtype=torch.float32,device=None,requires_grad=False)
m.dtype

torch.float32

In [24]:
m.type(torch.float16)

tensor([1.0000, 3.8008, 5.6992], dtype=torch.float16)

In [25]:
  n=m.type(torch.float16)

In [26]:
c=m*n
print(c)

tensor([ 1.0000, 14.4430, 32.4855])


In [27]:
x=torch.tensor([4,5,6],dtype=torch.int32)

In [28]:
y=m*x
print(y)

tensor([ 4.0000, 19.0000, 34.2000])


In [29]:
my_tensor=torch.rand(3,4)
my_tensor

tensor([[0.8665, 0.0640, 0.6643, 0.8921],
        [0.4785, 0.6269, 0.1937, 0.1630],
        [0.9273, 0.2742, 0.1196, 0.5456]])

In [30]:
print(f"Data type of tensor : {my_tensor.dtype}")
print(my_tensor.shape)
print(my_tensor.device)

Data type of tensor : torch.float32
torch.Size([3, 4])
cpu


In [31]:
# manupulating tensor


first = torch.tensor([3, 4, 5])
v = first + 10
print(v)


tensor([13, 14, 15])


In [32]:
sec=v-first
print(sec)

tensor([10, 10, 10])


In [33]:
a=torch.tensor([2,3,4,5])
b=torch.mul(a,10)
print("Answer :",b)

Answer : tensor([20, 30, 40, 50])


In [34]:
# matrix multiplication
v=b*b
print(v)

tensor([ 400,  900, 1600, 2500])


In [35]:
%%time
torch.matmul(b,b)

CPU times: user 151 µs, sys: 31 µs, total: 182 µs
Wall time: 306 µs


tensor(5400)

In [36]:
%%time
value=0
for i in range(len(b)):
  value+=b[i]*b[i]
print(value)

tensor(5400)
CPU times: user 454 µs, sys: 0 ns, total: 454 µs
Wall time: 499 µs


In [37]:
torch.matmul(torch.rand(6,4),torch.rand(4,4))

tensor([[1.1312, 1.4739, 1.6984, 0.7285],
        [0.7248, 0.9691, 0.6496, 0.3832],
        [0.1887, 0.2915, 0.3514, 0.2331],
        [0.4727, 0.4242, 0.2700, 0.4149],
        [1.6175, 1.4506, 1.5035, 1.1161],
        [0.9537, 0.7514, 1.3719, 0.5706]])



### number of columns in the first matrix must be equal to the number of rows in the second matrix




In [38]:
tensor_1=torch.tensor([[1,2,3,7],
                       [4,5,6,8],
                       [3,4,5,9]])

tensor_2=torch.tensor([[1,2,3,4],
                       [4,5,6,7],
                       [3,4,5,6],
                       [1,2,3,4]])

In [39]:
print("tensor 1 shape :",tensor_1.shape)
print("tensor 2 shape :",tensor_2.shape)

tensor 1 shape : torch.Size([3, 4])
tensor 2 shape : torch.Size([4, 4])


In [40]:
c=torch.matmul(tensor_1,tensor_2)
print(f"Matrix Multplication: \n\n{c}")

Matrix Multplication: 

tensor([[ 25,  38,  51,  64],
        [ 50,  73,  96, 119],
        [ 43,  64,  85, 106]])


In [41]:
x=torch.arange(0,100,10,dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [42]:
v=torch.min(x)
int(v)

0

In [43]:
n=torch.max(x)
int(n)

90

In [44]:
torch.mean(x)

tensor(45.)

In [45]:
x.argmin()

tensor(0)

In [46]:
x.argmax()

tensor(9)

In [47]:
a=torch.arange(1,10)
a.shape

torch.Size([9])

In [48]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
a.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [51]:
f=a.view(1,9)

In [52]:
# a.view(9,1)

In [53]:
f[:,0 : 4]=5


In [54]:
f

tensor([[5, 5, 5, 5, 5, 6, 7, 8, 9]])

In [55]:
st=torch.stack([a,a,a,a],dim=1)
st

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [56]:
c = torch.zeros(2, 1, 2, 1, 2)
c.size()

torch.Size([2, 1, 2, 1, 2])

In [57]:
c

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [58]:
c.ndim

5

In [59]:

y = torch.squeeze(c)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [60]:
d = torch.tensor([1, 2, 3, 4])
d

tensor([1, 2, 3, 4])

In [61]:
torch.unsqueeze(d, 0)

tensor([[1, 2, 3, 4]])

In [62]:
torch.unsqueeze(d, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [63]:
e=torch.randn(2, 3, 5) #(blocks,rows,columns)
e

tensor([[[-0.8111, -1.5582,  0.6404,  0.2504,  0.3252],
         [ 0.4698,  1.1988,  0.6387,  0.3831,  0.9341],
         [-1.9337,  1.6648, -0.2270,  0.0536, -0.5865]],

        [[ 1.0932,  1.2242, -0.4229,  0.4047,  2.6586],
         [-2.1658, -0.4269,  1.6696,  1.0036,  2.1669],
         [-0.1230,  2.2948, -0.0927,  0.7804,  2.2297]]])

In [64]:
e.size()

torch.Size([2, 3, 5])

In [65]:
torch.permute(e, (2, 0, 1))

tensor([[[-0.8111,  0.4698, -1.9337],
         [ 1.0932, -2.1658, -0.1230]],

        [[-1.5582,  1.1988,  1.6648],
         [ 1.2242, -0.4269,  2.2948]],

        [[ 0.6404,  0.6387, -0.2270],
         [-0.4229,  1.6696, -0.0927]],

        [[ 0.2504,  0.3831,  0.0536],
         [ 0.4047,  1.0036,  0.7804]],

        [[ 0.3252,  0.9341, -0.5865],
         [ 2.6586,  2.1669,  2.2297]]])

In [66]:
f=torch.rand(size=(224,224,3))
g=f.permute(2,0,1)
g

tensor([[[0.5377, 0.0876, 0.3956,  ..., 0.1474, 0.2588, 0.8212],
         [0.9722, 0.1285, 0.9618,  ..., 0.6675, 0.0391, 0.8996],
         [0.7914, 0.1523, 0.1044,  ..., 0.5538, 0.1068, 0.9443],
         ...,
         [0.4701, 0.3527, 0.2430,  ..., 0.2585, 0.1835, 0.8602],
         [0.3739, 0.4967, 0.7462,  ..., 0.0910, 0.0270, 0.2066],
         [0.1931, 0.5949, 0.9016,  ..., 0.7362, 0.6381, 0.1358]],

        [[0.7194, 0.7978, 0.1651,  ..., 0.9336, 0.0265, 0.5163],
         [0.7302, 0.6907, 0.5152,  ..., 0.5010, 0.0229, 0.6700],
         [0.6891, 0.9023, 0.0775,  ..., 0.7072, 0.3830, 0.9572],
         ...,
         [0.1692, 0.6077, 0.1746,  ..., 0.9678, 0.5252, 0.6272],
         [0.9502, 0.3514, 0.8753,  ..., 0.8842, 0.8163, 0.0896],
         [0.6217, 0.6860, 0.4653,  ..., 0.7693, 0.4489, 0.2432]],

        [[0.2780, 0.8102, 0.1814,  ..., 0.2405, 0.8733, 0.3763],
         [0.9831, 0.3123, 0.7852,  ..., 0.8234, 0.3826, 0.4307],
         [0.5504, 0.2865, 0.9611,  ..., 0.9828, 0.8299, 0.

In [67]:
f.shape

torch.Size([224, 224, 3])

In [68]:
g.shape

torch.Size([3, 224, 224])

In [69]:
h=torch.arange(1,10).reshape(1,3,3)
h

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [70]:
h.shape

torch.Size([1, 3, 3])

In [71]:
h[0][0][0]

tensor(1)

In [72]:
h[:,0]

tensor([[1, 2, 3]])

In [73]:
h[:,:,2]

tensor([[3, 6, 9]])

In [74]:
import numpy as np

In [75]:
array=np.arange(1.0,10.0)
print(array)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [76]:
tensor=torch.from_numpy(array)
print(tensor)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


In [77]:
array=array+1
array

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [78]:
tensor=torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [79]:
x=tensor.numpy()
x

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [80]:
x=x+1
x

array([2., 2., 2., 2., 2., 2., 2.], dtype=float32)

In [81]:
k=torch.rand(3,3)
k

tensor([[0.3621, 0.4551, 0.3455],
        [0.1934, 0.5814, 0.7084],
        [0.3095, 0.8284, 0.8625]])

In [82]:
l=torch.rand(3,3)
l

tensor([[0.8756, 0.3194, 0.7461],
        [0.7132, 0.2773, 0.3600],
        [0.1690, 0.6711, 0.5664]])

In [83]:
k==l

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [84]:
random_seed=42
torch.manual_seed(random_seed)
k1=torch.rand(3,3)
torch.manual_seed(random_seed)
k2=torch.rand(3,3)
print(k1)
print("===================================")
print(k2)
print("===================================")
print(k1==k2)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [85]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")  # Check if GPU is available
device

device(type='cuda', index=0)

In [86]:
j=torch.arange(1,10).reshape(1,3,3)
# a.reshape(1,3,3)
j

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [87]:
j[0][1]

tensor([4, 5, 6])

In [88]:
j[:,0]

tensor([[1, 2, 3]])

In [89]:
j[:,1]

tensor([[4, 5, 6]])

In [90]:
j[0][2][2]

tensor(9)

In [91]:
import numpy as np
array=np.arange(1.0,10.0)
tensor=torch.from_numpy(array)
array

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [92]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [93]:
array.dtype

dtype('float64')

In [94]:
torch.arange(2.0,20.0).dtype

torch.float32

In [95]:
array+=1
array

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
#tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [97]:
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [98]:

a=torch.rand(3,3)
b=torch.rand(3,3)

In [99]:
a

tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [100]:
b

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

In [101]:
a==b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [102]:
random_seed=42
torch.manual_seed(random_seed)
d=torch.rand(3,3)
torch.manual_seed(random_seed)
e=torch.rand(3,3)

In [103]:
print(d)
print("===============================")
print(e)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [104]:
d==e

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [105]:
!nvidia-smi

Sat Oct 28 15:24:43 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [106]:
torch.cuda.is_available()

True

In [108]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [109]:
device

'cuda'

In [110]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [111]:
tensor.device

device(type='cpu')

In [112]:
cpu_to_gpu=tensor.to(device)
cpu_to_gpu

tensor([1, 2, 3], device='cuda:0')