In [2]:
import torch
from torch import tensor

In [5]:
a=tensor([[1,2,3],
           [4,5,6],
           [7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
a.size()

torch.Size([3, 3])

In [7]:
a.shape

torch.Size([3, 3])

In [9]:
a[1,0],a[2,2]

(tensor(4), tensor(9))

In [10]:
a=torch.zeros((4,4))
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
b=torch.tensor([[1,2,3],
                [4,5,6]])
print(b)
print("===================================")
x=torch.zeros_like(b,dtype=int)
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [14]:
b=torch.ones((3,2))
b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [15]:
b=torch.full((4,3),8)
print(b)

tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])


In [16]:
d=torch.eye(4)
d

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [17]:
y=torch.randn((5,4))
y

tensor([[ 0.2165,  1.0570, -2.1107, -0.4390],
        [-0.9062, -2.1628, -0.9973, -0.8910],
        [-1.1708,  0.4783,  0.6891, -0.1995],
        [ 0.4632,  0.3888, -1.1057,  0.3474],
        [-0.0115,  0.2219,  0.8574, -0.5005]])

In [22]:
a=tensor([[1,2,3],
          [4,5,6],
          [7,8,9],
          [11,12,13]])

a[: 2,: 2]


tensor([[1, 2],
        [4, 5]])

In [23]:
b

tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])

In [26]:
a[: 4]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13]])

In [27]:
a[: 4,1:3]

tensor([[ 2,  3],
        [ 5,  6],
        [ 8,  9],
        [12, 13]])

In [31]:
a[0,1],a[1,1]

(tensor(2), tensor(5))

In [30]:
c=a.clone()
c

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13]])

In [32]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [34]:
torch.linspace(2,10,4) #(start,end,number of_samples)

tensor([ 2.0000,  4.6667,  7.3333, 10.0000])

In [35]:
a

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13]])

In [36]:
x=a>10
x

tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [37]:
a[x]

tensor([11, 12, 13])

In [38]:
a[a<10]

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a=tensor([1,2])
print(a.dtype)

torch.int64


In [40]:
x=torch.tensor([1,2,3],dtype=torch.float64)
x

tensor([1., 2., 3.], dtype=torch.float64)

In [41]:
x.dtype

torch.float64

In [42]:
x.type()

'torch.DoubleTensor'

In [44]:
x=tensor([1,2,3])
x.type()

'torch.LongTensor'

In [45]:
x = tensor([[1,2],[3,4]], dtype=torch.float64)
y = tensor([[5,6],[7,8]], dtype=torch.float64)

print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)


In [46]:
z=torch.add(x,y)
print(z)

tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)


In [47]:
print(x+y)

tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)


In [48]:
print(torch.matmul(x,y))

tensor([[19., 22.],
        [43., 50.]], dtype=torch.float64)


In [51]:
import torch

a = torch.tensor([[1, 2, 3],[12,3,3]])
b = torch.tensor([[4, 5, 6],[1,2,3]])

result = a * b
print(result)


tensor([[ 4, 10, 18],
        [12,  6,  9]])


In [53]:
a = tensor([1,2])
b = tensor([2,1])
torch.dot(a,b)

tensor(4)

In [54]:
x

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [55]:
torch.sum(x)

tensor(10., dtype=torch.float64)

In [58]:
print(torch.sum(x, dim=0))
print("=======================================")
print(torch.sum(x, dim=1))

tensor([4., 6.], dtype=torch.float64)
tensor([3., 7.], dtype=torch.float64)


In [62]:
x.T

tensor([[1., 3.],
        [2., 4.]], dtype=torch.float64)

In [64]:
# Concatenation [similar to np.concatenate]
x = torch.randn(2, 3)
y = torch.randn(2, 3)
print(x)
print("***************************************")
print(y)

tensor([[-1.5576,  1.7155, -0.3016],
        [ 0.0150,  0.0954, -0.0124]])
***************************************
tensor([[-1.1626,  1.1707,  0.6436],
        [ 2.9543, -2.0423, -0.6830]])


In [66]:
z = torch.cat([x, y], dim=1)
print(z)

tensor([[-1.5576,  1.7155, -0.3016, -1.1626,  1.1707,  0.6436],
        [ 0.0150,  0.0954, -0.0124,  2.9543, -2.0423, -0.6830]])


In [67]:
z = torch.cat([x, y], dim=0)
print(z)

tensor([[-1.5576,  1.7155, -0.3016],
        [ 0.0150,  0.0954, -0.0124],
        [-1.1626,  1.1707,  0.6436],
        [ 2.9543, -2.0423, -0.6830]])


In [68]:
# Stacking [Warning: stacking and concatenation is not same]
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = torch.stack([x, y], dim=0)
print(z)

tensor([[[ 2.4125, -1.3869,  1.2162],
         [ 0.7935,  1.1518, -0.0955]],

        [[ 0.1890, -1.2172, -0.5230],
         [-1.1338, -0.3677,  0.4516]]])


In [69]:
# Convert data type
x = tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
x.float()

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [70]:
x = tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = tensor([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [71]:
x = tensor([[1,2,3], [4,5,6]])
y = tensor([4,5])
(x.T+y).T

tensor([[ 5,  6,  7],
        [ 9, 10, 11]])