In [1]:
import torch
import numpy as np

In [2]:
x=[x for x in range(11)]
y=[1.6*x +4+np.random.normal(10,1) for x in x]

In [3]:
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
print(y)

[13.925467980122956, 16.058088339739413, 18.266340451890276, 18.512608990550017, 18.17477916591235, 21.355169289695166, 22.33008456588228, 26.09492620166479, 27.117804905485027, 27.93745966007431, 30.656806768125293]


In [5]:
x_train=x[: 9]
y_train=y[:9]
x_val=x[9:]
y_val=y[9:]

In [6]:
print(f"train data: {x_train}\nTest Data :{x_val}")

train data: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Test Data :[9, 10]


In [7]:
x_train = torch.tensor(x[:9], dtype=torch.float32).view(-1, 1)  # Reshape to (batch_size, 1)
y_train = torch.tensor(y[:9], dtype=torch.float32)
x_val = torch.tensor(x[9:], dtype=torch.float32).view(-1, 1)  # Reshape to (batch_size, 1)
y_val = torch.tensor(y[9:], dtype=torch.float32)

In [8]:
x_train

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])

In [9]:
x_val

tensor([[ 9.],
        [10.]])

In [10]:
y_train

tensor([13.9255, 16.0581, 18.2663, 18.5126, 18.1748, 21.3552, 22.3301, 26.0949,
        27.1178])

In [11]:
y_val

tensor([27.9375, 30.6568])

In [12]:
import torch.nn as nn
seq_model=nn.Sequential(nn.Linear(1,13),
                        nn.Tanh(),
                        nn.Linear(13,1))
seq_model

Sequential(
  (0): Linear(in_features=1, out_features=13, bias=True)
  (1): Tanh()
  (2): Linear(in_features=13, out_features=1, bias=True)
)

In [13]:
def train_loop(n_epochs,optimizer,model,loss_fn,x_train,x_val,y_train,y_val):
  for epoch in range(1,n_epochs+1):
    output_train=model(x_train)
    loss_train=loss_fn(output_train,y_train)
    output_val=model(x_val)
    loss_val=loss_fn(output_val,y_val)

    optimizer.zero_grad()
    loss_train.backward()
    optimizer.step()

    if epoch==1 or epoch %10000==0:
      print(f"Epoch  {epoch} | Training Loss:{loss_train.item():.4f} | "f"validation loss {loss_val.item():.4f}")

In [14]:
import torch.optim as optim
optimizer = optim.Adam(seq_model.parameters(), lr=1e-3)
train_loop(n_epochs = 50000,optimizer = optimizer,
    model = seq_model,
    loss_fn = nn.MSELoss(),
    x_train = x_train,
    x_val = x_val,
    y_train = y_train,
    y_val = y_val)

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([9])) that is different to the input size (torch.Size([9, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch  1 | Training Loss:402.5070 | validation loss 822.9568
Epoch  10000 | Training Loss:17.3061 | validation loss 83.8352
Epoch  20000 | Training Loss:17.2990 | validation loss 84.4685
Epoch  30000 | Training Loss:17.2990 | validation loss 84.5457
Epoch  40000 | Training Loss:17.2990 | validation loss 84.5364
Epoch  50000 | Training Loss:17.2990 | validation loss 84.5358


In [15]:
seq_model.state_dict()

OrderedDict([('0.weight',
              tensor([[-7.2871e-01],
                      [ 1.3317e+00],
                      [ 1.0345e-03],
                      [ 8.8633e-01],
                      [-1.0778e-03],
                      [ 2.4665e-03],
                      [ 2.4120e-04],
                      [ 1.0523e-03],
                      [-3.5554e-04],
                      [-7.7214e-01],
                      [-8.2886e-01],
                      [-7.6281e-01],
                      [-8.1325e-01]])),
             ('0.bias',
              tensor([-6.2485,  6.0860, -3.4983,  5.9897,  4.8811,  5.2397, -5.7917, -4.6159,
                       5.5393, -6.4952, -6.2752, -5.9500, -6.2209])),
             ('2.weight',
              tensor([[-1.0769,  1.2081, -1.6470,  1.5609,  1.4363,  1.5642, -1.4225, -1.5555,
                        1.5768, -1.4511, -1.4495, -1.5266, -1.5471]])),
             ('2.bias', tensor([1.1851]))])

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Generate data
X = [x for x in range(11)]
y = [1.6 * x + 4 + np.random.normal(10, 1) for x in X]

X_train = torch.tensor(X[:9], dtype=torch.float32).view(-1, 1)  # Reshape to (batch_size, 1)
y_train = torch.tensor(y[:9], dtype=torch.float32)
X_val = torch.tensor(X[9:], dtype=torch.float32).view(-1, 1)  # Reshape to (batch_size, 1)
y_val = torch.tensor(y[9:], dtype=torch.float32)

# Define the neural network model
seq_model = nn.Sequential(
    nn.Linear(1, 13),
    nn.Tanh(),
    nn.Linear(13, 1))

# Training loop
def training_loop(n_epochs, optimizer, model, loss_fn, X_train, X_val, y_train, y_val):
    for epoch in range(1, n_epochs + 1):
        output_train = model(X_train)  # Forward pass
        loss_train = loss_fn(output_train, y_train)  # Calculate loss
        output_val = model(X_val)
        loss_val = loss_fn(output_val, y_val)

        optimizer.zero_grad()  # Set gradients to zero
        loss_train.backward()  # Backward pass
        optimizer.step()  # Update model parameters

        if epoch == 1 or epoch % 10000 == 0:
            print(f"Epoch {epoch}, Training loss {loss_train.item():.4f},"f" Validation loss {loss_val.item():.4f}")

# Define the optimizer
optimizer = optim.SGD(seq_model.parameters(), lr=1e-3)

# Train the model
training_loop(
    n_epochs=500000,
    optimizer=optimizer,
    model=seq_model,
    loss_fn=nn.MSELoss(),
    X_train=X_train,
    X_val=X_val,
    y_train=y_train,
    y_val=y_val)


Epoch 1, Training loss 461.8124, Validation loss 896.8600
Epoch 10000, Training loss 17.2231, Validation loss 84.7394
Epoch 20000, Training loss 17.1920, Validation loss 83.1007
Epoch 30000, Training loss 17.1786, Validation loss 81.9968
Epoch 40000, Training loss 17.1723, Validation loss 81.0810
Epoch 50000, Training loss 17.1707, Validation loss 80.5349
Epoch 60000, Training loss 17.1705, Validation loss 80.3056
Epoch 70000, Training loss 17.1705, Validation loss 80.2210
Epoch 80000, Training loss 17.1705, Validation loss 80.1919
Epoch 90000, Training loss 17.1705, Validation loss 80.1791
Epoch 100000, Training loss 17.1705, Validation loss 80.1720
Epoch 110000, Training loss 17.1705, Validation loss 80.1661
Epoch 120000, Training loss 17.1705, Validation loss 80.1614
Epoch 130000, Training loss 17.1705, Validation loss 80.1571
Epoch 140000, Training loss 17.1705, Validation loss 80.1527
Epoch 150000, Training loss 17.1705, Validation loss 80.1484
